source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

pod 'ISAppearance', :path => '../'
pod 'ISAppearance/CodeGeneration', :path => '../'
pod 'ISAppearance/Categories', :path => '../'



